Apartaments/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('menu');
});

Route::get('/apartaments', function () {
    return view('welcome');
});
Route::get('/client', function () {
    return view('welcomeClients');
});
Route::get('/lloguer', function () {
    return view('welcomeLloguers');
});
Route::get('/usuari', function () {
    return view('welcomeUsuaris');
});

Route::resource('apartaments', ControladorApartaments::class);
Route::resource('clients', ControladorClients::class);
Route::resource('lloguers', ControladorLloguers::class);
Route::resource('usuaris', ControladorUsuaris::class);

Apartaments/resources/views/actualitza.blade.php
@extends('disseny')

@section('content')


    <div class="card mt-5">
        <div class="card-header">
            Actualització de dades
        </div>

        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('apartaments.update', $apartament->id) }}">
                <div class="form-group">
                    @csrf
                    @method('PATCH')
                    <label for="id">Id</label>
                    <input type="text" class="form-control" name="id" value="{{ $apartament->id }}" />
                </div>
                <div class="form-group">
                    <label for="Referenciacatastral">Ref catastral</label>
                    <input type="text" class="form-control" name="Referenciacatastral" value="{{ $apartament->Referenciacatastral }}" />
                </div>
                <div class="form-group">
                    <label for="Ciutat">Ciutat</label>
                    <input type="text" class="form-control" name="Ciutat" value="{{ $apartament->Ciutat }}" />
                </div>
                <div class="form-group">
                    <label for="Barri">Barri</label>
                    <input type="text" class="form-control" name="Barri" value="{{ $apartament->Barri }}" />
                </div>
                <div class="form-group">
                    <label for="Nomcarrer">Nom del carrer</label>
                    <input type="text" class="form-control" name="Nomcarrer" value="{{ $apartament->Nomcarrer }}" />
                </div>
                <div class="form-group">
                    <label for="Numcarrer">Nombre de porteria</label>
                    <input type="number" class="form-control" name="Numcarrer" value="{{ $apartament->Numcarrer }}" />
                </div>
                <div class="form-group">
                    <label for="Pis">Pis</label>
                    <input type="text" class="form-control" name="Pis" value="{{ $apartament->Pis }}" />
                </div>
                <div class="form-group">
                    <label for="Nombrellits">Nombre de llits</label>
                    <input type="number" class="form-control" name="Nombrellits" value="{{ $apartament->Nombrellits }}" />
                </div>
                <div class="form-group">
                    <label for="Nombrehabitacions">Nombre d'habitacions</label>
                    <input type="number" class="form-control" name="Nombrehabitacions" value="{{ $apartament->Nombrehabitacions }}" />
                </div>
                <div class="form-group">
                    <label for="Ascensor">Ascensor</label>
                    <input type="number" class="form-control" name="Ascensor" value="{{ $apartament->Ascensor }}" />
                </div>
                <div class="form-group">
                    <label for="Calefaccio">Calefaccio</label>
                    <input type="text" class="form-control" name="Calefaccio" value="{{ $apartament->Calefaccio }}" />
                </div>
                <div class="form-group">
                    <label for="Airecondicionat">Aire acondicionat</label>
                    <input type="number" class="form-control" name="Airecondicionat" value="{{ $apartament->Airecondicionat }}" />
                </div>

                <button type="submit" class="btn btn-block btn-danger">Actualitza</button>
            </form>
        </div>
    </div>
    <br><a href="{{ url('apartaments') }}">Accés directe a la Llista d'apartaments</a
@endsection

Apartaments/resources/views/actualitzaClient.blade.php
@extends('disseny')

@section('content')


    <div class="card mt-5">
        <div class="card-header">
            Actualització de dades
        </div>

        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('clients.update', $client->id) }}">
                <div class="form-group">
                    @csrf
                    @method('PATCH')
                    <label for="id">Id</label>
                    <input type="text" class="form-control" name="id" value="{{ $client->id }}" />
                </div>
                <div class="form-group">
                    <label for="Dni">Dni</label>
                    <input type="text" class="form-control" name="Dni" value="{{ $client->Dni }}" />
                </div>
                <div class="form-group">
                    <label for="Nomcognoms">Nom i cognoms</label>
                    <input type="text" class="form-control" name="Nomcognoms" value="{{ $client->Nomcognoms }}" />
                </div>
                <div class="form-group">
                    <label for="Edat">Edat</label>
                    <input type="num" class="form-control" name="Edat" value="{{ $client->Edat }}" />
                </div>
                <div class="form-group">
                    <label for="Tel">Telèfon</label>
                    <input type="number" class="form-control" name="Tel" value="{{ $client->Tel }}" />
                </div>
                <div class="form-group">
                    <label for="Adreca">Adreça</label>
                    <input type="text" class="form-control" name="Adreca" value="{{ $client->Adreca }}" />
                </div>
                <div class="form-group">
                    <label for="Ciutat">Ciutat</label>
                    <input type="text" class="form-control" name="Ciutat" value="{{ $client->Ciutat }}" />
                </div>
                <div class="form-group">
                    <label for="Pis">Pis</label>
                    <input type="text" class="form-control" name="Pis" value="{{ $client->Pis }}" />
                </div>
                <div class="form-group">
                    <label for="Email">Email</label>
                    <input type="text" class="form-control" name="Email" value="{{ $client->Email }}" />
                </div>
                <div class="form-group">
                    <label for="Tipustargeta">Tipus de targeta</label>
                    <input type="text" class="form-control" name="Tipustargeta" value="{{ $client->Tipustargeta }}" />
                </div>
                <div class="form-group">
                    <label for="Numtargeta">Nombre de targeta</label>
                    <input type="number" class="form-control" name="Numtargeta" value="{{ $client->Numtargeta }}" />
                </div>
                <button type="submit" class="btn btn-block btn-danger">Actualitza</button>
            </form>
        </div>
    </div>
    <br><a href="{{ url('clients') }}">Accés directe a la Llista de clients</a
@endsection

Apartaments/resources/views/actualitzaLloguer.blade.php
@extends('disseny')

@section('content')


    <div class="card mt-5">
        <div class="card-header">
            Actualització de dades
        </div>

        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('lloguers.update', $lloguer->id) }}">
                <div class="form-group">
                    <label for="Dni">Dni</label>
                    <input type="text" class="form-control" name="Dni" value="{{ $lloguer->Dni }}" />
                </div>
                <div class="form-group">
                    @csrf
                    @method('PATCH')
                    <label for="id">Id</label>
                    <input type="text" class="form-control" name="id" value="{{ $lloguer->id }}" />
                </div>
                <div class="form-group">
                    <label for="Datainici">Data d'inici</label>
                    <input type="date" class="form-control" name="Datainici" value="{{ $lloguer->Datainici }}" />
                </div>
                <div class="form-group">
                    <label for="Horainici">Hora d'inici</label>
                    <input type="num" class="form-control" name="Horainici" value="{{ $lloguer->Horainici }}" />
                </div>
                <div class="form-group">
                    <label for="Datafi">Data final</label>
                    <input type="date" class="form-control" name="Datafi" value="{{ $lloguer->Datafi }}" />
                </div>
                <div class="form-group">
                    <label for="Horafi">Hora final</label>
                    <input type="number" class="form-control" name="Horafi" value="{{ $lloguer->Horafi }}" />
                </div>
                <div class="form-group">
                    <label for="Lloclliuclaus">Lloc de lliurament de claus</label>
                    <input type="text" class="form-control" name="Lloclliuclaus" value="{{ $lloguer->Lloclliuclaus }}" />
                </div>
                <div class="form-group">
                    <label for="Llocdevclaus">Lloc de lliurament de claus</label>
                    <input type="text" class="form-control" name="Llocdevclaus" value="{{ $lloguer->Llocdevclaus }}" />
                </div>
                <div class="form-group">
                    <label for="Preudia">Preu per dia</label>
                    <input type="number" class="form-control" name="Preudia" value="{{ $lloguer->Preudia }}" />
                </div>
                <div class="form-group">
                    <label for="Diposit">Diposit</label>
                    <input type="number" class="form-control" name="Diposit" value="{{ $lloguer->Diposit }}" />
                </div>
                <div class="form-group">
                    <label for="Quantdiposit">Quantitat dipositada</label>
                    <input type="number" class="form-control" name="Quantdiposit" value="{{ $lloguer->Quantdiposit }}" />
                </div>
                <div class="form-group">
                    <label for="Tipusasseguranca">Tipus d'assegurança</label>
                    <input type="text" class="form-control" name="Tipusasseguranca" value="{{ $lloguer->Tipusasseguranca }}" />
                </div>


                <button type="submit" class="btn btn-block btn-danger">Actualitza</button>
            </form>
        </div>
    </div>
    <br><a href="{{ url('lloguers') }}">Accés directe a la Llista de lloguers</a
@endsection

Apartaments/resources/views/actualitzaUsuari.blade.php
@extends('disseny')

@section('content')


    <div class="card mt-5">
        <div class="card-header">
            Actualització de dades
        </div>

        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('usuaris.update', $usuari->id) }}">
                <div class="form-group">
                    @csrf
                    @method('PATCH')
                    <label for="Nomcognoms">Nom i cognoms</label>
                    <input type="text" class="form-control" name="Nomcognoms" value="{{ $usuari->Nomcognoms }}" />
                </div>
                <div class="form-group">
                    <label for="Email">Email</label>
                    <input type="text" class="form-control" name="Email" value="{{ $usuari->Email }}" />
                </div>
                <div class="form-group">
                    <label for="Contrasenya">Contrasenya</label>
                    <input type="text" class="form-control" name="Contrasenya" value="{{ $usuari->Contrasenya }}" />
                </div>
                <div class="form-group">
                    <label for="Tipus">Tipus d'empleat</label>
                    <input type="text" class="form-control" name="Tipus" value="{{ $usuari->Tipus }}" />
                </div>
                <div class="form-group">
                    <label for="Horaent">Hora d'entrada</label>
                    <input type="number" class="form-control" name="Horaent" value="{{ $usuari->Horaent }}" />
                </div>
                <div class="form-group">
                    <label for="Horasort">Hora de sortida</label>
                    <input type="number" class="form-control" name="Horasort" value="{{ $usuari->Horasort }}" />
                </div>


                <button type="submit" class="btn btn-block btn-danger">Actualitza</button>
            </form>
        </div>
    </div>
    <br><a href="{{ url('usuaris') }}">Accés directe a la Llista d'usuaris</a
@endsection

Apartaments/resources/views/disseny.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Projecte d'accés a BD MySQL amb Laravel 8</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    @yield('content')
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" type="text/js"></script>
</body>
</html>

Apartaments/resources/views/index.blade.php
@extends('disseny')

@section('content')

    <h1>Llista d'apartaments</h1>
    <div class="mt-5">
        @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
        @endif
        <table class="table">
            <thead>
            <tr class="table-primary">
                <td># Codi</td>
                <td>Ref Catastral</td>
                <td>Ciutat</td>
                <td>Barri</td>
                <td>Nom del carrer</td>
                <td>Nombre de porteria</td>
                <td>Pis</td>
                <td>Nombre de llits</td>
                <td>Nombre d'habitacions</td>
                <td>Ascensor</td>
                <td>Calefacció</td>
                <td>Aire acondicionat</td>
            </tr>
            </thead>
            <tbody>
            @foreach($apartament as $apart)
                <tr>
                    <td>{{$apart->id}}</td>
                    <td>{{$apart->Referenciacatastral}}</td>
                    <td>{{$apart->Ciutat}}</td>
                    <td>{{$apart->Barri}}</td>
                    <td>{{$apart->Nomcarrer}}</td>
                    <td>{{$apart->Numcarrer}}</td>
                    <td>{{$apart->Pis}}</td>
                    <td>{{$apart->Nombrellits}}</td>
                    <td>{{$apart->Nombrehabitacions}}</td>
                    <td>{{$apart->Ascensor}}</td>
                    <td>{{$apart->Calefaccio}}</td>
                    <td>{{$apart->Airecondicionat}}</td>
                    <td class="text-left">
                        <a href="{{ route('apartaments.edit', $apart->id)}}" class="btn btn-success btn-sm">Edita</a>
                        <form action="{{ route('apartaments.destroy', $apart->id)}}" method="post" style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm" type="submit">Esborra</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div>
            <br><a href="{{ url('apartaments/create') }}">Accés directe a la vista de creació d'apartaments</a>
            <br><a href="{{ url('/') }}">Accés directe al menú</a>
@endsection

Apartaments/resources/views/indexClient.blade.php
@extends('disseny')

@section('content')

    <h1>Llista de clients</h1>
    <div class="mt-5">
        @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
        @endif
        <table class="table">
            <thead>
            <tr class="table-primary">
                <td>id</td>
                <td># Dni</td>
                <td>Nom i cognoms</td>
                <td>Edat</td>
                <td>Telèfon</td>
                <td>Adreça</td>
                <td>Ciutat</td>
                <td>Pis</td>
                <td>Email</td>
                <td>Tipus de targeta</td>
                <td>Nombre de targeta</td>
            </tr>
            </thead>
            <tbody>
            @foreach($client as $cli)
                <tr>
                    <td>{{$cli->id}}</td>
                    <td>{{$cli->Dni}}</td>
                    <td>{{$cli->Nomcognoms}}</td>
                    <td>{{$cli->Edat}}</td>
                    <td>{{$cli->Tel}}</td>
                    <td>{{$cli->Adreca}}</td>
                    <td>{{$cli->Ciutat}}</td>
                    <td>{{$cli->Pis}}</td>
                    <td>{{$cli->Email}}</td>
                    <td>{{$cli->Tipustargeta}}</td>
                    <td>{{$cli->Numtargeta}}</td>
                    <td class="text-left">
                        <a href="{{ route('clients.edit', $cli->id)}}" class="btn btn-success btn-sm">Edita</a>
                        <form action="{{ route('clients.destroy', $cli->id)}}" method="post" style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm" type="submit">Esborra</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div>
            <br><a href="{{ url('clients/create') }}">Accés directe a la vista de creació de clients</a>
            <br><a href="{{ url('/') }}">Accés directe al menú</a>
@endsection

Apartaments/resources/views/indexLloguer.blade.php
@extends('disseny')

@section('content')

    <h1>Llista de lloguers</h1>
    <div class="mt-5">
        @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
        @endif
        <table class="table">
            <thead>
            <tr class="table-primary">
                <td># Dni</td>
                <td>id</td>
                <td>Data inici</td>
                <td>Hora inici</td>
                <td>Data final</td>
                <td>Hora final</td>
                <td>Lloc lliurament claus</td>
                <td>Lloc devolució claus</td>
                <td>Preu per dia</td>
                <td>Diposit</td>
                <td>Quantitat dipositada</td>
                <td>Tipus d'assegurança</td>
            </tr>
            </thead>
            <tbody>
            @foreach($lloguer as $llog)
                <tr>
                    <td>{{$llog->Dni}}</td>
                    <td>{{$llog->id}}</td>
                    <td>{{$llog->Datainici}}</td>
                    <td>{{$llog->Horainici}}</td>
                    <td>{{$llog->Datafi}}</td>
                    <td>{{$llog->Horafi}}</td>
                    <td>{{$llog->Lloclliuclaus}}</td>
                    <td>{{$llog->Llocdevclaus}}</td>
                    <td>{{$llog->Preudia}}</td>
                    <td>{{$llog->Diposit}}</td>
                    <td>{{$llog->Quantdiposit}}</td>
                    <td>{{$llog->Tipusasseguranca}}</td>
                    <td class="text-left">
                        <a href="{{ route('lloguers.edit', $llog->id)}}" class="btn btn-success btn-sm">Edita</a>
                        <form action="{{ route('lloguers.destroy', $llog->id)}}" method="post" style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm" type="submit">Esborra</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div>
            <br><a href="{{ url('lloguers/create') }}">Accés directe a la vista de creació de lloguers</a>
            <br><a href="{{ url('/') }}">Accés directe al menú</a>
@endsection

Apartaments/resources/views/indexUsuaris.blade.php
@extends('disseny')

@section('content')

    <h1>Llista d'usuaris</h1>
    <div class="mt-5">
        @if(session()->get('success'))
            <div class="alert alert-success">
                {{ session()->get('success') }}
            </div>
        @endif
        <table class="table">
            <thead>
            <tr class="table-primary">
                <td>id</td>
                <td>Nom i cognoms</td>
                <td>Email</td>
                <td>Contrasenya</td>
                <td>Tipus d'empleat</td>
                <td>Hora d'entrada</td>
                <td>Hora de sortida</td>
            </tr>
            </thead>
            <tbody>
            @foreach($usuari as $usu)
                <tr>
                    <td>{{$usu->id}}</td>
                    <td>{{$usu->Nomcognoms}}</td>
                    <td>{{$usu->Email}}</td>
                    <td>{{$usu->Contrasenya}}</td>
                    <td>{{$usu->Tipus}}</td>
                    <td>{{$usu->Horaent}}</td>
                    <td>{{$usu->Horasort}}</td>
                    <td class="text-left">
                        <a href="{{ route('usuaris.edit', $usu->id)}}" class="btn btn-success btn-sm">Edita</a>
                        <form action="{{ route('usuaris.destroy', $usu->id)}}" method="post" style="display: inline-block">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger btn-sm" type="submit">Esborra</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div>
            <br><a href="{{ url('usuaris/create') }}">Accés directe a la vista de creació d'usuaris</a>
            <br><a href="{{ url('/') }}">Accés directe al menú</a>
@endsection

Apartaments/resources/views/welcomeClients.blade.php
@extends('disseny')

@section('content')

    <h1>Aplicació d'administració de clients</h1>
    <div class="card mt-5">
        <div class="card-header">
            Afegeix un nou client
        </div>

        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('clients.store') }}">
                <div class="form-group">
                    <label for="id">Id</label>
                    <input type="num" class="form-control" name="id"/>
                </div>
                <div class="form-group">
                    @csrf
                    <label for="Dni">Dni</label>
                    <input type="text" class="form-control" name="Dni"/>
                </div>
                <div class="form-group">
                    <label for="Nomcognoms">Nom i Cognoms</label>
                    <input type="text" class="form-control" name="Nomcognoms"/>
                </div>
                <div class="form-group">
                    <label for="Edat">Edat</label>
                    <input type="number" class="form-control" name="Edat"/>
                </div>
                <div class="form-group">
                    <label for="Tel">Telèfon</label>
                    <input type="number" class="form-control" name="Tel"/>
                </div>
                <div class="form-group">
                    <label for="Adreca">Adreça</label>
                    <input type="text" class="form-control" name="Adreca"/>
                </div>
                <div class="form-group">
                    <label for="Ciutat">Ciutat</label>
                    <input type="text" class="form-control" name="Ciutat"/>
                </div>
                <div class="form-group">
                    <label for="Pis">Pis</label>
                    <input type="text" class="form-control" name="Pis"/>
                </div>
                <div class="form-group">
                    <label for="Email">Email</label>
                    <input type="text" class="form-control" name="Email"/>
                </div>
                <div class="form-group">
                    <label for="Tipustargeta">Tipus de targeta</label>
                    <input type="text" class="form-control" name="Tipustargeta"/>
                </div>
                <div class="form-group">
                    <label for="Numtargeta">Nombre de targeta</label>
                    <input type="number" class="form-control" name="Numtargeta"/>
                </div>
                <button type="submit" class="btn btn-block btn-primary">Envia</button>
            </form>
        </div>
    </div>
    <br><a href="{{ url('clients') }}">Accés directe a la Llista de clients</a>
    <br><a href="{{ url('/') }}">Accés directe al menú</a>
@endsection

Apartaments/resources/views/welcomeLloguers.blade.php
@extends('disseny')

@section('content')

    <h1>Aplicació d'administració de lloguers</h1>
    <div class="card mt-5">
        <div class="card-header">
            Afegeix un nou lloguer
        </div>

        <div class="card-body">
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <form method="post" action="{{ route('lloguers.store') }}">
                <div class="form-group">
                    @csrf
                    <label for="Dni">Dni</label>
                    <input type="text" class="form-control" name="Dni"/>
                </div>
                <div class="form-group">
                    <label for="id">id</label>
                    <input type="text" class="form-control" name="id"/>
                </div>
                <div class="form-group">
                    <label for="Datainici">Data d'inici</label>
                    <input type="date" class="form-control" name="Datainici"/>
                </div>
                <div class="form-group">
                    <label for="Horainici">Hora d'inici</label>
                    <input type="number" class="form-control" name="Horainici"/>
                </div>
                <div class="form-group">
                    <label for="Datafi">Data final</label>
                    <input type="date" class="form-control" name="Datafi"/>
                </div>
                <div class="form-group">
                    <label for="Horafi">Hora final</label>
                    <input type="number" class="form-control" name="Horafi"/>
                </div>
                <div class="form-group">
                    <label for="Lloclliuclaus">Lloc de lliurament de claus</label>
                    <input type="text" class="form-control" name="Lloclliuclaus"/>
                </div>
                <div class="form-group">
                    <label for="Llocdevclaus">Lloc de devolució de claus</label>
                    <input type="text" class="form-control" name="Llocdevclaus"/>
                </div>
                <div class="form-group">
                    <label for="Preudia">Preu per dia</label>
                    <input type="number" class="form-control" name="Preudia"/>
                </div>
                <div class="form-group">
                    <label for="Diposit">Diposit</label>
                    <input type="number" class="form-control" name="Diposit"/>
                </div>
                <div class="form-group">
                    <label for="Quantdiposit">Quantitat depositada</label>
                    <input type="number" class="form-control" name="Quantdiposit"/>
                </div>
                <div class="form-group">
                    <label for="Tipusasseguranca">Tipus d'assegurança</label>
                    <input type="text" class="form-control" name="Tipusasseguranca"/>
                </div>
                <button type="submit" class="btn btn-block btn-primary">Envia</button>
            </form>
        </div>
    </div>
    <br><a href="{{ url('lloguers') }}">Accés directe a la Llista de lloguers</a>
    <br><a href="{{ url('/') }}">Accés directe al menú</a>
@endsection